language: php
os: linux
cache: 
  - directories:
    - vendor
php:
- '7.3'
stages:
  - install
  - lint
  - test
jobs:
  include:
    - stage: install
      script: composer install --no-interaction
    - stage: lint
      script: composer lint
    - stage: test
      script: composer test
       

       
            

      
    
          
           


language: node_js
os: linux
cache: 
  - directories:
    - node_modules
node_js:
- '12'
- '11'
- '10'
stages:
  - install
  - lint
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: install
      script: npm ci
    - stage: lint
      script: npm run lint-check
    - stage: test
      script: npm test
    - stage: deploy
      script: echo "Not set yet"
       

       
            

      
    
          
           


